apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground-prove-ids-is-bad-sp-is-better

resources:
- ./namespace.yaml
- ./deployments/initialdelayseconds-deployment.yaml
- ./deployments/startupprobe-deployment.yaml
