apiVersion: apps/v1
kind: Deployment
metadata:
  name: initialdelayseconds-app
spec:
  selector:
    matchLabels:
      app: initialdelayseconds-app
  template:
    metadata:
      labels:
        app: initialdelayseconds-app
    spec:
      containers:
      - name: initialdelayseconds-app
        image: matoruru/dummyserver:1.0.1
        env:
        - name: PORT
          value: "8000"
        - name: TIME_TO_BE_READY
          value: "10000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: main-port
          containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthz
            port: main-port
          initialDelaySeconds: 60
          periodSeconds: 2
