apiVersion: apps/v1
kind: Deployment
metadata:
  name: startupprobe-app
spec:
  selector:
    matchLabels:
      app: startupprobe-app
  template:
    metadata:
      labels:
        app: startupprobe-app
    spec:
      containers:
      - name: startupprobe-app
        image: matoruru/dummyserver:1.0.1
        env:
        - name: PORT
          value: "8000"
        - name: TIME_TO_BE_READY
          value: "10000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: main-port
          containerPort: 8000
        startupProbe:
          httpGet:
            path: /healthz
            port: main-port
          failureThreshold: 100
          periodSeconds: 2
