apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-secret
spec:
  encryptedData:
    oidc.azure.clientSecret: AgBCwAyjQ6VkrLGbn0peCVQ+eqf+2PDTmxMp3zMzQs+YTeJJYwvfyL2un5coqD//aaNu/FS0LLiVDlR5IXHAOQJsfUSWsHfPat193HN5cVhQu3xE/zbzGUKQynp4PmtM7Z0hbsJBo3aFRtOz85CCbf5Y6Ox/Sgnx/Fs2PQ0ilhOrRZszPz+AUdCXGEVZufXEz6lXPXet58P/ILM6VdVKR9oC9mzJ85BkLWmc2Z2GM07CFjdAT4jtr0Gs6DEl8mztzE+IflnU/y46LSenMxV6yAmVhI5j4lFMNkznclI8jksWA7GshhUbLxl33rpZEsQFMswWnkAELhCW37aXJrw83gGG3zB6D+ENRnVKt10+ZIN8Vt4EfQMUkXA3a5e0FHq0yRNVUkvJ2TdRpbwAHYKZf4BQtA/MdDjzYTGH6B7igFHuorSkh6Z4r91JkJqIkyhGwZXJkg4rGXLRUamhgIQWg+V4YO47EzC1Tx+Ouqzb53l1FhUgToHFmWKBbHMSaw/cB9uamVFEl2nvCaz6KBTnluBvXhUu3aylHTOAVxmh6AkI0pqSc1cqfWy9vSqFZBs4mWNte8YPJcVEy45iiGIZk/7gAWh0bNrGOHuOqFkIl1cSJqKyMJdijffcS0cU5l5fSA3h5J7w3ty/zXTXcLmYMlii3mK2mS1PLd/YIlN8la/LxuezhBXz4f6u8GollOAMHT5NjBJBlgDsYaQ4RW7qqv6cVcwy0PVaoSqMumZWPzKzqumhgaUDqpldco10repRSHOlcAa4/2r+NQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-secret
