---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocd-secret
spec:
  encryptedData:
    oidc.azure.clientSecret: AgBLkFeGE09mz8BnFLATx29YADfXaDUW0io8aLQNHzxE5x5yFuigm5x0q/otbqoXUQYfPc5VKeuWPawiFhIWcQEimaejEDX2YG+adWqvzrEJ4D2dKkKenIW8NTHDZzhk56EsAk5b8QpVR/3oLXNb+1+1dDjXpBtjdnfVvlEDUhFSzOchh82ojp2h5L9IMMZKBSKh4Kcz8uKbhLwHvTEtrPIMa/E88vpw41lZnau94Gx5u+3lOH4xov/c2++T/6teMYk7pJ4K0lMSayL9n+8mIA0EzNrsq4rlK64Y5zlX53HXmG3xJrQmY4PrBaTsnuWvjR+oO95v+dMkDp8G1dthU73fegg6L6r5uCCFacqSHNNX0YPMmyiKJSF3rFdwUQyoMvkGBhUMQC6Irm+JYbLDcFw98+eN/xYDtWX33AH7T7CvoaTVLkKTYPADcxJQj6J/4CKYqrGaqGvDPhJu2AhBsliy39P1x07wcKW4UC2QwfZp5Q1R522qQ1a9z0h8cQQn+aoXgAAO8IHqdDihpdtdmSD2EL972cyNkAKrdnMZOjZnXru93QYhaWxGpFYTb0CH6Oyxxcfp4OCPTAIXBNdFczvytz8pjri3Fs/iPtNC8sKarfzQnYHvm99y/U2o8LJSJ1iDp5FZYXqEsbplP/L2IbKCyktNyQslTsmrCDTxI6z70nhwm2sxa6QJBfpVtv2e36k/hIOpG8cIW6KKzsE0TcU6WlITD2ibWJmTDUhPLqclS5ltMyL8S7f8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocd-secret
