apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
  - secretName: test-secret
    data:
    - objectName: mysecret
      key: secretkey
    type: Opaque
  parameters:
    keyvaultName: home-k8s-keyvault
    objects: |
      array:
        - |
          objectName: mysecret
          objectType: secret
    tenantId: 640dd2c2-336d-4abf-b0ee-0024877ea3fb