apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-generator
spec:
  selector:
    matchLabels:
      app: secret-generator
  template:
    metadata:
      labels:
        app: secret-generator
    spec:
      containers:
      - name: secret-generator
        image: busybox:latest
        command:
        - sh
        - -c
        - tail -f /dev/null
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
        volumeMounts:
        - name: test-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: test-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-sync
