apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matoruru+cert-manager@shgt.jp
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
    - selector:
        dnsZones:
          - matoru.ru
      dns01:
        route53:
          region: ap-northeast-1
          hostedZoneID: Z07443032LHCX00FJGX7O
          accessKeyID: AKIA4C5K34VVVNDTE3UB
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
