apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azurefile-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: charts/v1.30.0/azurefile-csi-driver
    repoURL: https://github.com/kubernetes-sigs/azurefile-csi-driver
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true