apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dolphinscheduler
  namespace: argocd
spec:
  destination:
    namespace: dolphinscheduler
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: playgrounds/0006/tools/manifests/dolphinscheduler
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true