apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: redis
    targetRevision: 19.1.0 #https://github.com/bitnami/charts/blob/c24cbd3ce19317ddb028bd0a47ff5851c02cadd6/bitnami/redis/Chart.yaml#L39C10-L39C16
    helm:
      releaseName: tyk-redis
      values: |
        # Tyk Redis
        architecture: standalone
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 15.2.4 #https://github.com/bitnami/charts/blob/c24cbd3ce19317ddb028bd0a47ff5851c02cadd6/bitnami/postgresql/Chart.yaml#L38C10-L38C16
    helm:
      releaseName: tyk-postgres
      values: |
        # Tyk PostgreSQL
        auth:
          database: tyk_analytic
        image:
          tag: 14.11.0
          debug: true
  - repoURL: https://helm.tyk.io/public/helm/charts
    chart: tyk-stack
    targetRevision: 1.3.0 #https://github.com/TykTechnologies/tyk-charts/blob/115d297efca20a013374de5cc47e273729e5d045/tyk-stack/Chart.yaml#L3C10-L3C15
    helm:
      releaseName: tyk
      values: |
        # Tyk
        global:
          adminUser:
            useSecretName: admin-secrets
          secrets:
            useSecretName: my-secrets
          redis:
            addrs: "{tyk-redis-master.$NAMESPACE.svc:6379}"
            passSecret:
              name: tyk-redis
              keyName: redis-password
          postgres:
            connectionStringSecret:
              name: postgres-secrets
              keyName: postgresUrl
  syncPolicy:
    automated:
      selfHeal: true
      prune: true