apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    path: redis
    targetRevision: main
    helm:
      releaseName: tyk-redis
      valueFiles:
      - ../values.yaml
  - repoURL: registry-1.docker.io/bitnamicharts
    path: postgresql
    targetRevision: main
    helm:
      releaseName: tyk-postgres
      valueFiles:
      - ../values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true