apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb2
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: playground-home-kubernetes/manifests/metallb
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}