apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress2
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: nginx-ingress
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: playground-home-kubernetes/manifests/nginx-ingress
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}