apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-http-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-http-app
  template:
    metadata:
      labels:
        app: sample-http-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - name: http-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    app: sample-http-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-port
  selector:
    app: sample-http-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /app1
        backend:
          serviceName: http-service
          servicePort: 80
