apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-nfs-standard
  mountOptions:
  - --use-attr-cache=false
  - --file-cache-timeout-in-seconds=0
  - -o direct_io=true
  csi:
    driver: blob.csi.azure.com
    volumeHandle: matorurustorage_data
    volumeAttributes:
      resourceGroup: Azure-Practice
      containerName: data
    nodeStageSecretRef:
      name: storage-account-secret
      namespace: default 