# A Workflow that create a GitHub Discussion post.
# GitHub Discussionに投稿するワークフロー

name: Create a Discussion post

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: octokit/graphql-action@v2.x
        id: get_id_objs
        name: Get repository ID and Discussion category (Announcements) ID
        with:
          query: |
            query {
              search(
                type: DISCUSSION,
                query: "repo:matoruru/playground category:Announcements",
                first: 1
              ) {
                edges {
                  node {
                    ... on Discussion {
                      category {
                        repository {
                          name,
                          id
                        },
                        name,
                        id
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check result object
        run: |
          echo Result Object: '${{ steps.get_id_objs.outputs.data }}'
          echo Repository Name: '${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.repository.name }}'
          echo Repository ID: '${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.repository.id }}'
          echo Category Name: '${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.name }}'
          echo Category ID: '${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.id }}'
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      # - uses: actions/github-script@v7
      #   name: Get IDs from GraphQL result object
      #   id: get_ids
      #   with:
      #     script: |
      #       console.log('hi')

      # - uses: octokit/graphql-action@v2.x
      #   with:
      #     query: |
      #       mutation {
      #         createDiscussion(input: {repositoryId: "R_kgDOK6_K-w", categoryId: "DIC_kwDOK6_K-84CcXrZ", body: "This is created by GraphQL API!", title: "The title"}) {
      #           discussion {
      #             id
      #           }
      #         }
      #       }
      #     variables: |
      #       owner: ${{ github.event.repository.owner.name }}
      #       repo: ${{ github.event.repository.name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
