# A Workflow that create a GitHub Discussion post.
# GitHub Discussionに投稿するワークフロー

name: Create a Discussion post to a specific category

on:
  workflow_dispatch:
    inputs:
      category:
        required: true
        default: Announcements
      title:
        required: true
        default: This post is created by GitHUb Action!
      body:
        required: true
        default: This post is created by GitHUb Action via GraphQL API!
  workflow_call:
    inputs:
      category:
        type: string
        required: true
        default: Announcements
      title:
        type: string
        required: true
        default: This post is created by GitHUb Action!
      body:
        type: string
        required: true
        default: This post is created by GitHUb Action via GraphQL API!

jobs:
  post_discussion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set default variables as outputs
        id: default_variables
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_OUTPUT
      - uses: octokit/graphql-action@v2.x
        id: get_id_objs
        name: Get repository ID and Discussion category (${{ github.event.inputs.category || inputs.category  }}) ID
        with:
          query: |
            query {
              search(
                type: DISCUSSION,
                query: "repo:${{ steps.default_variables.outputs.GITHUB_REPOSITORY }} category:${{ github.event.inputs.category || inputs.category }}",
                first: 1
              ) {
                edges {
                  node {
                    ... on Discussion {
                      category {
                        repository {
                          name,
                          id
                        },
                        name,
                        id
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GraphQL result
        run: |
          echo Result Object: "${{ steps.get_id_objs.outputs.data }}"
      - uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation {
              createDiscussion(
                input: {
                  repositoryId: "${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.repository.id }}",
                  categoryId: "${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.id }}",
                  title: "${{ github.event.inputs.title || inputs.title }}",
                  body: "${{ github.event.inputs.body || inputs.body }}"
                }
              ) {
                discussion {
                  id
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
