# A Workflow that create a GitHub Discussion post.
# GitHub Discussionに投稿するワークフロー

name: Create a Discussion post to a specific category

on:
  workflow_dispatch:
    inputs:
      category:
        required: true
        default: Announcements

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set default variables as outputs
        id: default_variables
        run: |
          echo "A=$GITHUB_REPOSITORY_ID" >> $GITHUB_OUTPUTS
      - uses: octokit/graphql-action@v2.x
        id: get_id_objs
        name: Get repository ID and Discussion category (${{ github.event.inputs.category }}) ID
        with:
          query: |
            query {
              search(
                type: DISCUSSION,
                query: "repo:matoruru/playground category:${{ github.event.inputs.category }}",
                first: 1
              ) {
                edges {
                  node {
                    ... on Discussion {
                      category {
                        repository {
                          name,
                          id
                        },
                        name,
                        id
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GraphQL result
        run: |
          echo Result Object: "${{ steps.get_id_objs.outputs.data }}"
          echo \"${{ steps.default_variables.outputs.GITHUB_REPOSITORY_ID }}\"
      - uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation {
              createDiscussion(
                input: {repositoryId: "${{ steps.default_variables.outputs.GITHUB_REPOSITORY_ID }}",
                categoryId: "${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.id }}",
                body: "This post is created by GraphQL API!", title: "This post is created by GitHub Action"}
              ) {
                discussion {
                  id
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
