# A Workflow that create a GitHub Discussion post.
# GitHub Discussionに投稿するワークフロー

name: Create a Discussion post

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: octokit/graphql-action@v2.x
        id: get_id_objs
        name: Get repository ID and Discussion category (Announcements) ID
        with:
          query: |
            query {
              search(
                type: DISCUSSION,
                query: "repo:matoruru/playground category:Announcements",
                first: 1
              ) {
                edges {
                  node {
                    ... on Discussion {
                      category {
                        repository {
                          name,
                          id
                        },
                        name,
                        id
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GraphQL result
        run: |
          echo Result Object: "${{ steps.get_id_objs.outputs.data }}"
      - uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation {
              createDiscussion(
                input: {repositoryId: "${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.repository.id }}",
                categoryId: "${{ fromJSON(steps.get_id_objs.outputs.data).search.edges[0].node.category.id }}",
                body: "This post is created by GraphQL API!", title: "This post is created by GitHub Action"}
              ) {
                discussion {
                  id
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
