name: 1D Matrix Example

on:
  workflow_dispatch:
    inputs:
      Alice_age:
        type: number
        default: 10
      Bob_age:
        type: number
        default: 18
      Charlie_age:
        type: number
        default: 12

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Alice
            age: ${{ inputs.Alice_age }}
          - name: Bob
            age: ${{ inputs.Bob_age }}
          - name: Charlie
            age: ${{ inputs.Charlie_age }}

    runs-on: raspi-playground
    name: Run for ${{ matrix.name }} (${{ matrix.age }})

    steps:
      - run: |
          echo 'Hello, ${{ matrix.name }}(${{ matrix.age }})!'
