name: 1D Matrix Example

on:
  workflow_dispatch: {}

env:
  Alice_age: 10
  Bob_age: 18
  Charlie_age: 12

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Alice
            age: ${{ env.Alice_age }}
          - name: Bob
            age: ${{ env.Bob_age }}
          - name: Charlie
            age: ${{ env.Charlie_age }}

    runs-on: raspi-playground
    name: Run for ${{ matrix.name }} (${{ matrix.age }})

    steps:
      - run: |
          echo 'Hello, ${{ matrix.name }}(${{ matrix.age }})!'
