# This is a basic workflow that is manually triggered

name: Kubescape scan (JUnit XML)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Kubescape
      run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

    - name: add path
      run: echo "/home/runner/.kubescape/bin" >> $GITHUB_PATH

    - name: type kubescape
      run: type kubescape

    - uses: actions/checkout@v4

    - run: ls -la

    - name: 'Scan Kustomize manifest (format: JUnit XML)'
      run: kubescape scan framework nsa --format junit --verbose -- playground-kubescape-github-action/manifest/ > scan-result-junit.xml

    # https://github.com/marketplace/actions/test-reporter#example
    - name: Scan result
      uses: dorny/test-reporter@v1
      with:
        name: Kubescape scan result
        path: scan-result-jaunit.xml
        reporter: jest-junit