# This is a basic workflow that is manually triggered

name: Kubescape scan (Pretty print)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Kubescape
      run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

    - name: add path
      run: echo "/home/runner/.kubescape/bin" >> $GITHUB_PATH

    - name: type kubescape
      run: type kubescape

    - uses: actions/checkout@v4

    - run: ls -la

    - name: 'Scan Kustomize manifest (format: Pretty print)'
      run: |
        echo '# Kubescape Manifest scan result' > result.txt
        echo >> result.txt
        echo '```' >> result.txt
        kubescape scan framework nsa --verbose -- playground-kubescape-github-action/manifest/ >> result.txt
        echo '```' >> result.txt

    - name: Output to summary
      run: cat result.txt >> $GITHUB_STEP_SUMMARY