name: Set variables

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: raspi-playground
    steps:
    - uses: actions/checkout@v3
    - name: Install GitHub CLI
      run: |
        # https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt-get update \
        && sudo apt-get install gh -y
    - name: Set variables
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        echo "TEST_VAR=test-value" >> variables.env
        gh variable set -f variables.env
