name: Switch display name based on environment

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        options:
        - Dev
        - Staging

jobs:
  Release:
    name: Release ${{ inputs.env }}
    runs-on: raspi-playground
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
