name: CI

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  ci:
    environment: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.9.0]
    steps:
      - run: echo hello
  build:
    needs: ['ci']
    environment: build
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
