name: Try Resume a cancelled job
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: raspi-playground
    steps:
    - run: |
        for ((i = 1; i <= 30; i++))
        do
          echo $i
          sleep 1
        done
  job2:
    needs: ['job1']
    runs-on: raspi-playground
    steps:
    - run: |
        for ((i = 1; i <= 30; i++))
        do
          echo $i
          sleep 1
        done
  job3:
    needs: ['job2']
    runs-on: raspi-playground
    steps:
    - run: |
        for ((i = 1; i <= 30; i++))
        do
          echo $i
          sleep 1
        done
