# This is a basic workflow that is manually triggered

name: Use a tag in JS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  branches:
    - main
  tags:
    - 'v*.*.*'
    - 'v*.*.*-rc*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/github-script@v7
      name: js script
      with:
        script: |
          const fullRef = '${{ github.ref_name }}'
          console.log('Git Ref: ', fullRef)
          const tag = fullRef.split('/')[2]
          console.log('Tag name: ', tag)
          
